# Project Group 8

Members & student numbers:
- Ioan Birgaoanu-Acaei (4545249)
- Fleur Cauwels (5316154)
- Maartje Vennegoor (5375894)
- Pip Busser (5253993)
- Wendy Chi (5340942)

# 1. Introduction

COVID-19 is the infectious disease that emerged at the end of 2019. Its consequences were visible in the Netherlands from January 2020 until May 2022. As a result, the government introduced measures such as keeping 1.5 meters distance, wearing face masks, encouraging people to work from home as much as possible, banning contact professions, and closing schools. These measures have led to significant improvements in technology for remote learning and working, which has resulted in changes in people's travel behaviour. 

This project investigates how the travel behaviour of Dutch people has changed after the pandemic compared to before the pandemic. The research focuses on people's travel behaviour between urban and rural areas. It looks at changes in trip frequency, distance, and purpose. Furthermore, it examines the role of remote work and digitalization. This question is important because transport systems and road capacity are planned years in advance. This research provides insights into which shifts caused by the pandemic persist across different population groups. As a result, the government gained a better understanding to optimize the Dutch infrastructure with respect to roads and railways.

# 2. Research Objective

**“How did the COVID-19 pandemic reshape travel behaviour in urban versus rural regions of the Netherlands?”**

The main objective of this research is to examine whether COVID-19 influenced the travel behaviour of Dutch citizens. To capture this potential impact, we will compare data from 2019 (pre-pandemic) with data from 2023 (post-pandemic). By contrasting these two periods, we aim to identify whether travel patterns have shifted as a result of COVID-19.

To refine the analysis, a distinction is made between two segments of the Dutch population: residents of urban areas and those in rural areas. This division is particularly relevant, as the spatial context strongly shapes mobility patterns. In urban areas, higher population density and closer proximity of facilities often lead to shorter and more frequent trips, while in rural areas longer distances between destinations typically result in different travel needs and behaviours. Comparing these two contexts provides insights into how the pandemic may have reshaped travel behaviour across varying spatial environments.

This research does not distinguish between different modes of transport, but instead analyses overall travel behaviour. This approach is chosen because the available datasets only allow for reliable measurement of total mobility, rather than separate modal splits.

**Sub objectives:** 
1. Is there a difference in the average distance travelled per trip on each day of the week between urban and rural residents in 2019 and 2023?
2. Is there a difference in the motives for travel (work versus leisure) between urban and rural residents of the Netherlands in 2019 and 2023?
3. Is there a difference in the amount of transport use among students from rural and urban areas in the Netherlands between 2019 and 2023?

We include the sub-questions above because these perspectives capture important distinctions in travel behaviour that help answer the main research question. Travel behaviour often differs between weekdays and weekends, as weekdays are usually linked to work or school and weekends more to leisure. Looking at these patterns helps to see how routines may have changed between 2019 and 2023. Travel motives can further explain these changes, since the pandemic led to more working from home, which likely reduced commuting and shifted the balance between work- and leisure-related trips. Studying these aspects for urban and rural residents shows whether the impact of COVID-19 differed across contexts.

## 3. Datasets

**Datafile 1**

Data file 1 provides information categorized by degree of urbanization. It includes data on transport mode usage, broken down by day of the week and by travel motives. The data can be found throughout the years of 2019 to 2023.
https://opendata.cbs.nl/statline/#/CBS/nl/dataset/85055NED/table?ts=1759410636287  

**Datafile 2**

Data file 2 zooms in on the mobility of different personal characteristics. It includes data about students' characteristics and how much they travel each year. This data can also be found throughout the years 2019 and 2023. https://opendata.cbs.nl/#/CBS/nl/dataset/84713NED/table?ts=1760342193753

**Datafile 3**

Data file 3 provides an overview of the address density per municipality. Every municipality is divided into five categories depending on their urbanity. https://opendata.cbs.nl/#/CBS/nl/dataset/85067NED/table?dl=78795

## Importing datafile 1 ##

In [54]:
"""Importing datafile 1"""
df = pd.read_csv('Dataset1.csv',\
    delimiter=';',\
    encoding='utf-8-sig',
    skiprows=4) #skip the first 4 rows because they don't contain any needed data
df
#filter "perioden": 2019 and 2023
#filter "verplaatsingskenmerken": all "Dag van verplaatsing"
#filter" reismotieven": "Totaal", "Van en naar het werk", "Zakelijk, beroepsmatig", "Winkelen, boodschappen doen",
# "Visite, logeren", "Uitgaan, sport, hobby", "Toeren, wandelen"

,Unnamed: 0,Onderwerp,Gemiddelde afstand per verplaatsing,Gemiddelde afstand per verplaatsing.1,Gemiddelde afstand per verplaatsing.2,Gemiddelde afstand per verplaatsing.3,Gemiddelde afstand per verplaatsing.4,Gemiddelde afstand per verplaatsing.5,Gemiddelde afstand per verplaatsing.6,Gemiddelde afstand per verplaatsing.7,...,Gemiddelde reisduur per verplaatsing.2,Gemiddelde reisduur per verplaatsing.3,Gemiddelde reisduur per verplaatsing.4,Gemiddelde reisduur per verplaatsing.5,Gemiddelde reisduur per verplaatsing.6,Gemiddelde reisduur per verplaatsing.7,Gemiddelde reisduur per verplaatsing.8,Gemiddelde reisduur per verplaatsing.9,Gemiddelde reisduur per verplaatsing.10,Gemiddelde reisduur per verplaatsing.11
0,NaN,Regiokenmerken,Nederland,Nederland,Zeer sterk stedelijk,Zeer sterk stedelijk,Sterk stedelijk,Sterk stedelijk,Matig stedelijk,Matig stedelijk,...,Zeer sterk stedelijk,Zeer sterk stedelijk,Sterk stedelijk,Sterk stedelijk,Matig stedelijk,Matig stedelijk,Weinig stedelijk,Weinig stedelijk,Niet stedelijk,Niet stedelijk
1,NaN,Perioden,2019,2023,2019,2023,2019,2023,2019,2023,...,2019,2023,2019,2023,2019,2023,2019,2023,2019,2023
2,Verplaatsingskenmerken,Reismotieven,reizigerskilometers,reizigerskilometers,reizigerskilometers,reizigerskilometers,reizigerskilometers,reizigerskilometers,reizigerskilometers,reizigerskilometers,...,minuten,minuten,minuten,minuten,minuten,minuten,minuten,minuten,minuten,minuten
3,Totaal,Totaal,"13,29","11,76","12,11","10,57","13,17","11,76","13,24","11,80",...,"29,55","29,29","27,08","26,78","26,51","25,96","26,24","25,82","28,06","26,73"
4,Totaal,Van en naar het werk,"19,26","18,33","17,26","16,35","19,30","18,84","19,99","18,50",...,"32,46","31,86","30,36","29,99","29,24","27,92","27,86","27,54","27,74","26,19"
5,Totaal,"Zakelijk, beroepsmatig","30,56","26,44","27,80","22,91","31,01","28,18","31,77","28,57",...,"38,68","34,01","36,93","36,49","36,42","35,98","36,99","31,57","36,07","32,59"
6,Totaal,"Winkelen, boodschappen doen","5,75","5,23","4,31","3,95","5,32","5,02","6,46","5,50",...,"15,48","15,21","14,74","14,38","15,02","14,33","14,98","14,72","16,07","13,82"
7,Totaal,"Visite, logeren","21,41","19,34","24,55","22,16","22,09","19,18","20,04","18,39",...,"37,59","36,40","30,16","27,84","26,88","26,19","25,24","24,09","28,56","28,03"
8,Totaal,"Uitgaan, sport, hobby","13,09","12,63","11,52","11,22","13,54","13,75","12,96","11,92",...,"31,35","32,46","29,53","30,24","28,63","27,61","25,79","27,69","29,31","26,97"
9,Totaal,"Toeren, wandelen","9,52","7,12","8,78","6,91","9,67","7,00","9,51","7,02",...,"77,48","67,24","67,13","56,00","64,53","56,11","69,06","55,65","67,21","58,41"
10,Verplaatsing op zondag,Totaal,"18,33","14,52","17,31","13,53","19,10","14,47","17,27","14,86",...,"40,27","36,44","35,08","33,03","35,31","33,50","33,60","33,45","43,14","33,72"
11,Verplaatsing op zondag,Van en naar het werk,"15,43","13,58","13,77","9,86","16,27","10,30","14,94","16,95",...,"27,23","28,36","25,85","19,46","28,72","21,88","23,09","27,82",.,.
12,Verplaatsing op zondag,"Zakelijk, beroepsmatig",.,"23,36",.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
13,Verplaatsing op zondag,"Winkelen, boodschappen doen","7,55","6,60","4,70","5,50","7,78","5,98","9,01","6,60",...,"16,00","17,32","16,01","15,56","20,57","14,50","16,71","16,49","22,01","16,36"
14,Verplaatsing op zondag,"Visite, logeren","28,19","23,53","32,18","27,37","31,44","24,86","22,85","23,63",...,"42,93","40,01","34,69","30,67","29,65","29,20","29,38","25,55","32,78","26,17"
15,Verplaatsing op zondag,"Uitgaan, sport, hobby","17,67","15,68","17,35","15,43","18,75","16,70","18,92","13,74",...,"37,96","37,27","35,02","34,49","31,72","33,62","27,92","32,17","34,65","29,82"
16,Verplaatsing op zondag,"Toeren, wandelen","14,50","9,02","14,03","7,69","14,26","8,97","12,57","9,08",...,"104,19","75,16","88,34","65,71","83,29","68,86","88,49","69,46","100,73","75,46"
17,Verplaatsing op maandag,Totaal,"12,41","11,21","10,97","9,91","12,34","10,88","12,39","11,44",...,"27,00","27,83","25,53","25,50","24,34","25,50","24,94","25,41","26,86","26,32"
18,Verplaatsing op maandag,Van en naar het werk,"19,86","18,66","18,18","16,39","19,74","19,45","21,02","18,73",...,"32,37","31,54","30,98","29,94","30,82","28,80","29,22","27,83","26,50","29,26"
19,Verplaatsing op maandag,"Zakelijk, beroepsmatig","30,77","26,22","30,93","25,16","30,06","23,08","31,03","33,00",...,"39,15","35,20","35,34","31,89","33,41","37,16","35,94","32,46",.,.
20,Verplaatsing op maandag,"Winkelen, boodschappen doen","4,71","4,63","3,22","3,43","3,92","4,26",.,"5,31",...,"13,73","14,08","13,19","13,13","14,74","14,07","13,01","14,70","15,30","12,02"
21,Verplaatsing op maandag,"Visite, logeren","16,86","17,53","18,08","23,27","20,45","16,12","9,81","13,98",...,"32,66","37,88","30,39","26,21","17,98","20,97","24,64","25,32",.,"24,84"
22,Verplaatsing op maandag,"Uitgaan, sport, hobby","10,89","10,77","7,97","8,62","10,21","10,10","10,08","11,20",...,"27,14","28,24","26,18","26,00","25,70","27,01","26,30","24,56",.,"26,88"
23,Verplaatsing op maandag,"Toeren, wandelen","6,68","6,01","6,43","6,04","6,53","6,17","7,33","5,80",...,"64,94","65,52","57,07","50,63","49,52","53,24","57,23","50,97","53,87","53,71"
24,Verplaatsing op dinsdag,Totaal,"13,12","11,37","11,30","9,80","13,53","11,20","12,88","12,21",...,"27,92","27,55","26,71","26,24","25,73","26,06","26,80","24,77","26,60","27,21"
25,Verplaatsing op dinsdag,Van en naar het werk,"21,06","19,69","18,78","16,86","21,58","21,35","22,41","19,37",...,"33,86","32,52","32,23","32,51","30,56","29,26","28,75","28,28","29,48","28,55"
26,Verplaatsing op dinsdag,"Zakelijk, beroepsmatig","33,82","26,18","26,72","24,21","36,29","26,62","25,39","28,50",...,"41,30","37,14","40,55","34,48","33,53","37,12","44,46","36,61",.,.
27,Verplaatsing op dinsdag,"Winkelen, boodschappen doen","4,79","4,77","3,62","3,05","5,01","4,68","4,71","6,05",...,"14,24","14,65","14,05","14,30","12,78","15,05","13,37","14,65","12,44","13,75"
28,Verplaatsing op dinsdag,"Visite, logeren","15,89","16,49","15,96","18,80","19,02","15,40","17,17","16,29",...,"30,16","32,00","29,40","26,81","25,62","26,60","21,44","22,29","25,01","30,09"
29,Verplaatsing op dinsdag,"Uitgaan, sport, hobby","9,97","9,05","9,54","6,90","9,63","9,20","9,61","10,65",...,"29,11","26,84","26,62","27,13","24,92","26,02","24,10","22,99","27,66","26,35"
30,Verplaatsing op dinsdag,"Toeren, wandelen","8,62","5,95","7,20","5,62",.,"5,51","7,96","5,98",...,"72,23","61,75","57,95","48,87","62,59","54,32","66,90","52,23","53,78","48,10"
31,Verplaatsing op woensdag,Totaal,"12,23","11,24","11,74","10,02","11,51","11,27","12,67","11,40",...,"28,43","27,58","25,25","25,76","26,25","24,73","24,04","24,97","24,76","24,41"
32,Verplaatsing op woensdag,Van en naar het werk,"18,97","19,06","18,17","17,73","18,09","19,95","19,73","17,90",...,"33,15","33,56","30,35","31,03","29,74","27,52","27,10","29,09","26,69","26,72"
33,Verplaatsing op woensdag,"Zakelijk, beroepsmatig","31,09","28,26","29,15","25,17","34,57","30,74","36,43","29,51",...,"39,86","33,24","42,30","39,57","41,44","37,37","33,80","31,79",.,.
34,Verplaatsing op woensdag,"Winkelen, boodschappen doen","4,99","4,62","4,51","3,18","4,06","4,13","5,37","4,59",...,"15,47","14,80","13,27","13,05","13,45","13,69","13,94","14,98","19,24","14,52"
35,Verplaatsing op woensdag,"Visite, logeren","17,86","15,44","24,12","14,97","16,68","15,32","18,49","17,85",...,"37,23","28,07","26,32","25,09","27,06","25,10","21,43","19,93","25,69","22,01"
36,Verplaatsing op woensdag,"Uitgaan, sport, hobby","9,83","10,81","8,35","10,48","10,51","10,72","10,29","11,99",...,"27,01","32,73","25,18","26,37","30,71","25,01","21,33","25,66","19,29","21,71"
37,Verplaatsing op woensdag,"Toeren, wandelen","8,10","6,25","6,40","6,01","8,64","6,79","9,35","6,25",...,"65,21","58,06","64,99","58,49","59,07","53,06","53,74","48,82","65,90","52,17"
38,Verplaatsing op donderdag,Totaal,"12,96","11,55","11,47","10,41","13,38","11,66","12,67","11,14",...,"26,71","29,12","26,86","26,32","25,59","25,07","25,33","25,78","26,65","25,03"
39,Verplaatsing op donderdag,Van en naar het werk,"20,33","19,35","17,75","18,45","21,64","19,01","20,05","19,42",...,"32,90","34,05","31,69","30,68","30,07","29,29","27,58","28,03","28,22","26,53"
40,Verplaatsing op donderdag,"Zakelijk, beroepsmatig","31,65","28,32","27,21","21,97","35,45","30,11","38,46","33,26",...,"39,59","35,94","40,81","39,72","40,85","40,14","33,86","31,88",.,.
41,Verplaatsing op donderdag,"Winkelen, boodschappen doen","5,34","4,92","3,65","3,34","5,02","4,78","5,08","5,54",...,"15,16","14,10","14,59","14,36","13,76","14,62","15,44","13,96","16,34","13,37"
42,Verplaatsing op donderdag,"Visite, logeren","16,76","16,67","20,61","20,04","15,27","18,91","15,65","13,13",...,"32,84","39,59","26,50","28,88","21,75","24,61","22,76","21,92",.,"21,68"
43,Verplaatsing op donderdag,"Uitgaan, sport, hobby","10,88","9,80","10,26","8,94","11,37","11,23","9,84","8,28",...,"26,17","29,43","25,81","28,07","28,44","26,17","23,56","28,55","24,78","24,75"
44,Verplaatsing op donderdag,"Toeren, wandelen","8,05","6,86","6,46","8,02","8,40","6,44","8,65","5,94",...,"56,30","67,15","66,24","52,38","60,24","47,86","68,59","52,80","57,09","52,58"
45,Verplaatsing op vrijdag,Totaal,"12,46","10,89","11,47","9,36","11,52","10,85","12,86","11,11",...,"29,29","27,29","25,12","24,25","24,56","23,41","25,15","23,65","25,62","24,12"
46,Verplaatsing op vrijdag,Van en naar het werk,"17,95","16,91","15,04","13,71","17,14","17,12","19,43","19,14",...,"32,35","28,73","28,67","28,50","27,33","27,88","29,26","24,71","27,94","23,21"
47,Verplaatsing op vrijdag,"Zakelijk, beroepsmatig","26,84","24,87","25,47","20,19","20,74","30,19","30,52","22,55",...,"34,29","28,76","27,33","34,96","33,91","30,46","36,83","29,30",.,.
48,Verplaatsing op vrijdag,"Winkelen, boodschappen doen","5,63","5,01","4,96","3,88","4,57","4,80","6,87","5,07",...,"16,83","14,83","14,24","14,12","14,69","13,56","14,89","14,39","14,71","12,36"
49,Verplaatsing op vrijdag,"Visite, logeren","19,40","16,32","21,52","18,33","19,67","13,87","21,11","14,59",...,"37,62","33,87","29,36","23,45","27,80","23,30","25,76","24,47","19,31","29,74"
50,Verplaatsing op vrijdag,"Uitgaan, sport, hobby","13,84","13,97","11,81","11,02","14,67","16,91","14,15","13,21",...,"33,08","31,67","31,59","31,14","28,27","26,81","26,76","27,80","33,10","27,92"
51,Verplaatsing op vrijdag,"Toeren, wandelen","7,43","6,27","7,66","5,66","7,71","5,32","6,48","6,64",...,"75,11","63,15","58,85","49,41","56,53","48,30","61,17","55,68","49,91","53,08"
52,Verplaatsing op zaterdag,Totaal,"13,12","12,38","12,07","11,77","12,84","12,79","13,36","11,40",...,"30,63","31,17","27,80","28,20","26,81","25,88","26,12","25,15","27,96","28,17"
53,Verplaatsing op zaterdag,Van en naar het werk,"13,68","12,82","10,96","11,44","13,64","12,37","12,89","12,18",...,"25,68","25,63","24,18","24,82","20,86","20,12","21,93","25,13","27,38","19,86"
54,Verplaatsing op zaterdag,"Zakelijk, beroepsmatig","17,37","18,76",.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
55,Verplaatsing op zaterdag,"Winkelen, boodschappen doen","6,93","5,98","4,96","4,95","6,79","6,00","7,75","5,79",...,"16,19","16,40","16,75","15,50","16,79","14,87","16,54","14,78","16,43","14,93"
56,Verplaatsing op zaterdag,"Visite, logeren","23,90","22,45","27,98","25,13","22,00","21,68","25,25","21,30",...,"40,43","38,54","30,06","29,63","30,21","28,71","25,50","26,07","35,44","35,41"
57,Verplaatsing op zaterdag,"Uitgaan, sport, hobby","15,19","15,65","12,71","13,84","15,59","17,99","14,45","13,43",...,"34,92","36,57","32,02","34,90","28,98","27,46","27,88","29,28","31,98","28,66"
58,Verplaatsing op zaterdag,"Toeren, wandelen","11,15","8,90","9,87","8,98","11,15","9,20","12,98","8,72",...,"88,22","76,84","72,98","64,14","73,34","62,98","77,27","57,27","71,15","69,46"
59,Bron: CBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df_copy = df.copy() #make a copy of the original dataframe
new_header = pd.MultiIndex.from_arrays(df.iloc[0:3].values) #make row with index 0,1 en 2 part of the column index. These rows don't contain any data and they should be part of the column index
df_copy.columns = new_header #make these rows part of the new column indexes
df_new = df_copy.iloc[3:] 
df_new

                          NaN               Regiokenmerken  \
                          NaN                     Perioden
       Verplaatsingskenmerken                 Reismotieven
3                     Totaal                        Totaal
4                     Totaal          Van en naar het werk
5                     Totaal        Zakelijk, beroepsmatig
6                     Totaal   Winkelen, boodschappen doen
7                     Totaal               Visite, logeren
8                     Totaal         Uitgaan, sport, hobby
9                     Totaal              Toeren, wandelen
10     Verplaatsing op zondag                       Totaal
11     Verplaatsing op zondag         Van en naar het werk
12     Verplaatsing op zondag       Zakelijk, beroepsmatig
13     Verplaatsing op zondag  Winkelen, boodschappen doen
14     Verplaatsing op zondag              Visite, logeren
15     Verplaatsing op zondag        Uitgaan, sport, hobby
16     Verplaatsing op zondag             Toeren, wandelen
17    Verplaatsing op maandag                       Totaal
18    Verplaatsing op maandag         Van en naar het werk
19    Verplaatsing op maandag       Zakelijk, beroepsmatig
20    Verplaatsing op maandag  Winkelen, boodschappen doen
21    Verplaatsing op maandag              Visite, logeren
22    Verplaatsing op maandag        Uitgaan, sport, hobby
23    Verplaatsing op maandag             Toeren, wandelen
24    Verplaatsing op dinsdag                       Totaal
25    Verplaatsing op dinsdag         Van en naar het werk
26    Verplaatsing op dinsdag       Zakelijk, beroepsmatig
27    Verplaatsing op dinsdag  Winkelen, boodschappen doen
28    Verplaatsing op dinsdag              Visite, logeren
29    Verplaatsing op dinsdag        Uitgaan, sport, hobby
30    Verplaatsing op dinsdag             Toeren, wandelen
31   Verplaatsing op woensdag                       Totaal
32   Verplaatsing op woensdag         Van en naar het werk
33   Verplaatsing op woensdag       Zakelijk, beroepsmatig
34   Verplaatsing op woensdag  Winkelen, boodschappen doen
35   Verplaatsing op woensdag              Visite, logeren
36   Verplaatsing op woensdag        Uitgaan, sport, hobby
37   Verplaatsing op woensdag             Toeren, wandelen
38  Verplaatsing op donderdag                       Totaal
39  Verplaatsing op donderdag         Van en naar het werk
40  Verplaatsing op donderdag       Zakelijk, beroepsmatig
41  Verplaatsing op donderdag  Winkelen, boodschappen doen
42  Verplaatsing op donderdag              Visite, logeren
43  Verplaatsing op donderdag        Uitgaan, sport, hobby
44  Verplaatsing op donderdag             Toeren, wandelen
45    Verplaatsing op vrijdag                       Totaal
46    Verplaatsing op vrijdag         Van en naar het werk
47    Verplaatsing op vrijdag       Zakelijk, beroepsmatig
48    Verplaatsing op vrijdag  Winkelen, boodschappen doen
49    Verplaatsing op vrijdag              Visite, logeren
50    Verplaatsing op vrijdag        Uitgaan, sport, hobby
51    Verplaatsing op vrijdag             Toeren, wandelen
52   Verplaatsing op zaterdag                       Totaal
53   Verplaatsing op zaterdag         Van en naar het werk
54   Verplaatsing op zaterdag       Zakelijk, beroepsmatig
55   Verplaatsing op zaterdag  Winkelen, boodschappen doen
56   Verplaatsing op zaterdag              Visite, logeren
57   Verplaatsing op zaterdag        Uitgaan, sport, hobby
58   Verplaatsing op zaterdag             Toeren, wandelen
59                  Bron: CBS                          NaN

             Nederland                     Zeer sterk stedelijk  \
                  2019                2023                 2019
   reizigerskilometers reizigerskilometers  reizigerskilometers
3                13,29               11,76                12,11
4                19,26               18,33                17,26
5                30,56               26,44                27,80
6                 5,75                5,23                 4,31
7                21,41               19,34                24,55
8                13,09               12,63                11,52
9                 9,52                7,12                 8,78
10               18,33               14,52                17,31
11               15,43               13,58                13,77
12                   .               23,36                    .
13                7,55                6,60                 4,70
14               28,19               23,53                32,18
15               17,67               15,68                17,35
16               14,50                9,02                14,03
17               12,41               11,21                10,97
18               19,86               18,66                18,18
19               30,77               26,22                30,93
20                4,71                4,63                 3,22
21               16,86               17,53                18,08
22               10,89               10,77                 7,97
23                6,68                6,01                 6,43
24               13,12               11,37                11,30
25               21,06               19,69                18,78
26               33,82               26,18                26,72
27                4,79                4,77                 3,62
28               15,89               16,49                15,96
29                9,97                9,05                 9,54
30                8,62                5,95                 7,20
31               12,23               11,24                11,74
32               18,97               19,06                18,17
33               31,09               28,26                29,15
34                4,99                4,62                 4,51
35               17,86               15,44                24,12
36                9,83               10,81                 8,35
37                8,10                6,25                 6,40
38               12,96               11,55                11,47
39               20,33               19,35                17,75
40               31,65               28,32                27,21
41                5,34                4,92                 3,65
42               16,76               16,67                20,61
43               10,88                9,80                10,26
44                8,05                6,86                 6,46
45               12,46               10,89                11,47
46               17,95               16,91                15,04
47               26,84               24,87                25,47
48                5,63                5,01                 4,96
49               19,40               16,32                21,52
50               13,84               13,97                11,81
51                7,43                6,27                 7,66
52               13,12               12,38                12,07
53               13,68               12,82                10,96
54               17,37               18,76                    .
55                6,93                5,98                 4,96
56               23,90               22,45                27,98
57               15,19               15,65                12,71
58               11,15                8,90                 9,87
59                 NaN                 NaN                  NaN

                           Sterk stedelijk                      \
                  2023                2019                2023
   reizigerskilometers reizigerskilometers reizigerskilometers
3                10,57               13,17               11,76
4                16,35               19,30               18,84
5                22,91               31,01               28,18
6                 3,95                5,32                5,02
7                22,16               22,09               19,18
8                11,22               13,54               13,75
9                 6,91                9,67                7,00
10               13,53               19,10               14,47
11                9,86               16,27               10,30
12                   .                   .                   .
13                5,50                7,78                5,98
14               27,37               31,44               24,86
15               15,43               18,75               16,70
16                7,69               14,26                8,97
17                9,91               12,34               10,88
18               16,39               19,74               19,45
19               25,16               30,06               23,08
20                3,43                3,92                4,26
21               23,27               20,45               16,12
22                8,62               10,21               10,10
23                6,04                6,53                6,17
24                9,80               13,53               11,20
25               16,86               21,58               21,35
26               24,21               36,29               26,62
27                3,05                5,01                4,68
28               18,80               19,02               15,40
29                6,90                9,63                9,20
30                5,62                   .                5,51
31               10,02               11,51               11,27
32               17,73               18,09               19,95
33               25,17               34,57               30,74
34                3,18                4,06                4,13
35               14,97               16,68               15,32
36               10,48               10,51               10,72
37                6,01                8,64                6,79
38               10,41               13,38               11,66
39               18,45               21,64               19,01
40               21,97               35,45               30,11
41                3,34                5,02                4,78
42               20,04               15,27               18,91
43                8,94               11,37               11,23
44                8,02                8,40                6,44
45                9,36               11,52               10,85
46               13,71               17,14               17,12
47               20,19               20,74               30,19
48                3,88                4,57                4,80
49               18,33               19,67               13,87
50               11,02               14,67               16,91
51                5,66                7,71                5,32
52               11,77               12,84               12,79
53               11,44               13,64               12,37
54                   .                   .                   .
55                4,95                6,79                6,00
56               25,13               22,00               21,68
57               13,84               15,59               17,99
58                8,98               11,15                9,20
59                 NaN                 NaN                 NaN

       Matig stedelijk                      ... Zeer sterk stedelijk          \
                  2019                2023  ...                 2019    2023
   reizigerskilometers reizigerskilometers  ...              minuten minuten
3                13,24               11,80  ...                29,55   29,29
4                19,99               18,50  ...                32,46   31,86
5                31,77               28,57  ...                38,68   34,01
6                 6,46                5,50  ...                15,48   15,21
7                20,04               18,39  ...                37,59   36,40
8                12,96               11,92  ...                31,35   32,46
9                 9,51                7,02  ...                77,48   67,24
10               17,27               14,86  ...                40,27   36,44
11               14,94               16,95  ...                27,23   28,36
12                   .                   .  ...                    .       .
13                9,01                6,60  ...                16,00   17,32
14               22,85               23,63  ...                42,93   40,01
15               18,92               13,74  ...                37,96   37,27
16               12,57                9,08  ...               104,19   75,16
17               12,39               11,44  ...                27,00   27,83
18               21,02               18,73  ...                32,37   31,54
19               31,03               33,00  ...                39,15   35,20
20                   .                5,31  ...                13,73   14,08
21                9,81               13,98  ...                32,66   37,88
22               10,08               11,20  ...                27,14   28,24
23                7,33                5,80  ...                64,94   65,52
24               12,88               12,21  ...                27,92   27,55
25               22,41               19,37  ...                33,86   32,52
26               25,39               28,50  ...                41,30   37,14
27                4,71                6,05  ...                14,24   14,65
28               17,17               16,29  ...                30,16   32,00
29                9,61               10,65  ...                29,11   26,84
30                7,96                5,98  ...                72,23   61,75
31               12,67               11,40  ...                28,43   27,58
32               19,73               17,90  ...                33,15   33,56
33               36,43               29,51  ...                39,86   33,24
34                5,37                4,59  ...                15,47   14,80
35               18,49               17,85  ...                37,23   28,07
36               10,29               11,99  ...                27,01   32,73
37                9,35                6,25  ...                65,21   58,06
38               12,67               11,14  ...                26,71   29,12
39               20,05               19,42  ...                32,90   34,05
40               38,46               33,26  ...                39,59   35,94
41                5,08                5,54  ...                15,16   14,10
42               15,65               13,13  ...                32,84   39,59
43                9,84                8,28  ...                26,17   29,43
44                8,65                5,94  ...                56,30   67,15
45               12,86               11,11  ...                29,29   27,29
46               19,43               19,14  ...                32,35   28,73
47               30,52               22,55  ...                34,29   28,76
48                6,87                5,07  ...                16,83   14,83
49               21,11               14,59  ...                37,62   33,87
50               14,15               13,21  ...                33,08   31,67
51                6,48                6,64  ...                75,11   63,15
52               13,36               11,40  ...                30,63   31,17
53               12,89               12,18  ...                25,68   25,63
54                   .                   .  ...                    .       .
55                7,75                5,79  ...                16,19   16,40
56               25,25               21,30  ...                40,43   38,54
57               14,45               13,43  ...                34,92   36,57
58               12,98                8,72  ...                88,22   76,84
59                 NaN                 NaN  ...                  NaN     NaN

   Sterk stedelijk         Matig stedelijk         Weinig stedelijk          \
              2019    2023            2019    2023             2019    2023
           minuten minuten         minuten minuten          minuten minuten
3            27,08   26,78           26,51   25,96            26,24   25,82
4            30,36   29,99           29,24   27,92            27,86   27,54
5            36,93   36,49           36,42   35,98            36,99   31,57
6            14,74   14,38           15,02   14,33            14,98   14,72
7            30,16   27,84           26,88   26,19            25,24   24,09
8            29,53   30,24           28,63   27,61            25,79   27,69
9            67,13   56,00           64,53   56,11            69,06   55,65
10           35,08   33,03           35,31   33,50            33,60   33,45
11           25,85   19,46           28,72   21,88            23,09   27,82
12               .       .               .       .                .       .
13           16,01   15,56           20,57   14,50            16,71   16,49
14           34,69   30,67           29,65   29,20            29,38   25,55
15           35,02   34,49           31,72   33,62            27,92   32,17
16           88,34   65,71           83,29   68,86            88,49   69,46
17           25,53   25,50           24,34   25,50            24,94   25,41
18           30,98   29,94           30,82   28,80            29,22   27,83
19           35,34   31,89           33,41   37,16            35,94   32,46
20           13,19   13,13           14,74   14,07            13,01   14,70
21           30,39   26,21           17,98   20,97            24,64   25,32
22           26,18   26,00           25,70   27,01            26,30   24,56
23           57,07   50,63           49,52   53,24            57,23   50,97
24           26,71   26,24           25,73   26,06            26,80   24,77
25           32,23   32,51           30,56   29,26            28,75   28,28
26           40,55   34,48           33,53   37,12            44,46   36,61
27           14,05   14,30           12,78   15,05            13,37   14,65
28           29,40   26,81           25,62   26,60            21,44   22,29
29           26,62   27,13           24,92   26,02            24,10   22,99
30           57,95   48,87           62,59   54,32            66,90   52,23
31           25,25   25,76           26,25   24,73            24,04   24,97
32           30,35   31,03           29,74   27,52            27,10   29,09
33           42,30   39,57           41,44   37,37            33,80   31,79
34           13,27   13,05           13,45   13,69            13,94   14,98
35           26,32   25,09           27,06   25,10            21,43   19,93
36           25,18   26,37           30,71   25,01            21,33   25,66
37           64,99   58,49           59,07   53,06            53,74   48,82
38           26,86   26,32           25,59   25,07            25,33   25,78
39           31,69   30,68           30,07   29,29            27,58   28,03
40           40,81   39,72           40,85   40,14            33,86   31,88
41           14,59   14,36           13,76   14,62            15,44   13,96
42           26,50   28,88           21,75   24,61            22,76   21,92
43           25,81   28,07           28,44   26,17            23,56   28,55
44           66,24   52,38           60,24   47,86            68,59   52,80
45           25,12   24,25           24,56   23,41            25,15   23,65
46           28,67   28,50           27,33   27,88            29,26   24,71
47           27,33   34,96           33,91   30,46            36,83   29,30
48           14,24   14,12           14,69   13,56            14,89   14,39
49           29,36   23,45           27,80   23,30            25,76   24,47
50           31,59   31,14           28,27   26,81            26,76   27,80
51           58,85   49,41           56,53   48,30            61,17   55,68
52           27,80   28,20           26,81   25,88            26,12   25,15
53           24,18   24,82           20,86   20,12            21,93   25,13
54               .       .               .       .                .       .

## Dataset 2 ##

In [49]:
"""Importing datafile 2"""
df2 = pd.read_csv('Dataset2_niet_stedelijk.csv',\
    delimiter=';',\
    encoding='utf-8-sig',
    skiprows=4) #skip the first 4 rows because they don't contain any needed data
df2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Unnamed: 0  \
NaN                  Geslacht                      Totaal mannen en vrouwen                       Totaal mannen en vrouwen                       Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Mannen                                         Mannen                                         Mannen                                  Mannen                                  Mannen                                  Mannen                                  Vrouwen                                        Vrouwen                                        Vrouwen                                 Vrouwen                                                                  Vrouwen
                     Onderwerp                     Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand   Gemiddeld per persoon per dag |Reisduur
                     Perioden                      2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                                                        2019
Reismotieven         Persoonskenmerken             aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                                                      minuten
Totaal               Participatie:student/scholier 2,80                                           2,76                                           30,81                                   31,16                                   76,98                                   70,27                                   2,71                                           2,87                                           31,75                                   30,33                                   80,38                                   71,97                                   2,89                                           2,67                                           29,83                                   31,94                                                                      73,44
Van en naar het werk Participatie:student/scholier 0,17                                           0,17                                           .                                       .                                       .                                       3,10                                    .                                              .                                              .                                       .                                       .                                       .                                       .                                              .                                              .                                       .                                                                              .
Bron: CBS            NaN                           NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                                                          NaN

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Unnamed: 1
NaN                  Geslacht                      Totaal mannen en vrouwen                       Totaal mannen en vrouwen                       Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Mannen                                         Mannen                                         Mannen                                  Mannen                                  Mannen                                  Mannen                                  Vrouwen                                        Vrouwen                                        Vrouwen                                 Vrouwen                                                                  Vrouwen
                     Onderwerp                     Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand   Gemiddeld per persoon per dag |Reisduur
                     Perioden                      2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                                                        2023
Reismotieven         Persoonskenmerken             aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                                                      minuten
Totaal               Participatie:student/scholier 2,80                                           2,76                                           30,81                                   31,16                                   76,98                                   70,27                                   2,71                                           2,87                                           31,75                                   30,33                                   80,38                                   71,97                                   2,89                                           2,67                                           29,83                                   31,94                                                                      68,69
Van en naar het werk Participatie:student/scholier 0,17                                           0,17                                           .                                       .                                       .                                       3,10                                    .                                              .                                              .                                       .                                       .                                       .                                       .                                              .                                              .                                       .                                                                              .
Bron: CBS            NaN                           NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                                                          NaN

## Dataset 3 ##

In [53]:
"""Importing datafile 2"""
df3 = pd.read_csv('Dataset2_zeer_sterk_stedelijk.csv',\
    delimiter=';',\
    encoding='utf-8-sig',
    skiprows=4) #skip the first 4 rows because they don't contain any needed data
df3

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Unnamed: 0  \
NaN                  Geslacht                      Totaal mannen en vrouwen                       Totaal mannen en vrouwen                       Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Mannen                                         Mannen                                         Mannen                                  Mannen                                  Mannen                                  Mannen                                  Vrouwen                                        Vrouwen                                        Vrouwen                                 Vrouwen                                                                  Vrouwen
                     Onderwerp                     Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand   Gemiddeld per persoon per dag |Reisduur
                     Perioden                      2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                                                        2019
Reismotieven         Persoonskenmerken             aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                                                      minuten
Totaal               Participatie:student/scholier 2,65                                           2,51                                           23,95                                   20,01                                   71,17                                   71,08                                   2,62                                           2,48                                           21,91                                   19,88                                   70,84                                   71,00                                   2,69                                           2,53                                           26,01                                   20,14                                                                      71,51
Van en naar het werk Participatie:student/scholier 0,15                                           0,12                                           1,43                                    0,81                                    3,64                                    2,73                                    0,16                                           0,10                                           1,63                                    0,79                                    4,10                                    2,51                                    0,13                                           0,14                                           1,22                                    0,84                                                                        3,17
Bron: CBS            NaN                           NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                                                          NaN

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Unnamed: 1
NaN                  Geslacht                      Totaal mannen en vrouwen                       Totaal mannen en vrouwen                       Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Totaal mannen en vrouwen                Mannen                                         Mannen                                         Mannen                                  Mannen                                  Mannen                                  Mannen                                  Vrouwen                                        Vrouwen                                        Vrouwen                                 Vrouwen                                                                  Vrouwen
                     Onderwerp                     Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Reisduur Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Verplaatsingen  Gemiddeld per persoon per dag |Afstand  Gemiddeld per persoon per dag |Afstand   Gemiddeld per persoon per dag |Reisduur
                     Perioden                      2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                    2019                                    2023                                    2019                                           2023                                           2019                                    2023                                                                        2023
Reismotieven         Persoonskenmerken             aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                     minuten                                 minuten                                 aantal                                         aantal                                         reizigerskilometers                     reizigerskilometers                                                      minuten
Totaal               Participatie:student/scholier 2,65                                           2,51                                           23,95                                   20,01                                   71,17                                   71,08                                   2,62                                           2,48                                           21,91                                   19,88                                   70,84                                   71,00                                   2,69                                           2,53                                           26,01                                   20,14                                                                      71,16
Van en naar het werk Participatie:student/scholier 0,15                                           0,12                                           1,43                                    0,81                                    3,64                                    2,73                                    0,16                                           0,10                                           1,63                                    0,79                                    4,10                                    2,51                                    0,13                                           0,14                                           1,22                                    0,84                                                                        2,94
Bron: CBS            NaN                           NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                     NaN                                     NaN                                     NaN                                            NaN                                            NaN                                     NaN                                                                          NaN

# 4. Contribution Statement

**Ioan Birgaoanu-Acaei**:
- Background research
- Introduction

**Fleur Cauwels**:
- Background research
- Refining proposal

**Maartje Vennegoor**:
- Background research
- Research objective

**Pip Busser**:
- Background research
- Research Objective

**Wendy Chi**:
- Background research 
- Organise files and set up GitHub

# 5. Data Pipeline